#!/bin/bash

echo "📦 Huddle - Ready to push to GitHub"
echo "===================================="
echo ""
echo "Repository: https://github.com/simply-ask/huddle"
echo ""
echo "The code is committed locally. To push to GitHub, you need to:"
echo ""
echo "Option 1: Using GitHub CLI (recommended)"
echo "-----------------------------------------"
echo "1. Install GitHub CLI: brew install gh"
echo "2. Authenticate: gh auth login"
echo "3. Push: git push -u origin main"
echo ""
echo "Option 2: Using Personal Access Token"
echo "--------------------------------------"
echo "1. Go to GitHub Settings > Developer settings > Personal access tokens"
echo "2. Generate a new token with 'repo' scope"
echo "3. Push using: git push https://YOUR_TOKEN@github.com/simply-ask/huddle.git main"
echo ""
echo "Option 3: Using SSH"
echo "-------------------"
echo "1. Set up SSH key: https://docs.github.com/en/authentication/connecting-to-github-with-ssh"
echo "2. Change remote: git remote set-url origin git@github.com:simply-ask/huddle.git"
echo "3. Push: git push -u origin main"
echo ""
echo "Current status:"
git status --short --branch
echo ""
echo "Files committed: $(git ls-tree -r HEAD --name-only | wc -l) files"
echo ""