# Generated by Django 4.2.23 on 2025-09-02 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceSetupToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meeting_id", models.CharField(max_length=8)),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "huddle_voice_setup_token",
            },
        ),
        migrations.CreateModel(
            name="SpeakerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "voice_signature",
                    models.JSONField(default=dict, help_text="Audio fingerprint data"),
                ),
                (
                    "sample_audio",
                    models.FileField(
                        blank=True,
                        help_text="Reference audio sample",
                        upload_to="voice-samples/%Y/%m/",
                    ),
                ),
                (
                    "meetings_count",
                    models.IntegerField(
                        default=0, help_text="Number of meetings attended"
                    ),
                ),
                (
                    "accuracy_score",
                    models.FloatField(
                        default=0.0, help_text="Recognition accuracy over time"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Company/team owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "huddle_speaker_profile",
                "unique_together": {("organization", "email")},
            },
        ),
    ]
