# Generated by Django 5.2.5 on 2025-09-01 16:25

import apps.audio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(upload_to=apps.audio.models.huddle_recording_upload_path)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(max_length=10)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meeting')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingparticipant')),
            ],
            options={
                'db_table': 'huddle_audio_recording',
            },
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('key_points', models.JSONField(default=list, help_text='List of key discussion points')),
                ('action_items', models.JSONField(default=list, help_text='List of action items with assignees')),
                ('participants_summary', models.JSONField(default=dict, help_text='Speaking time and participation stats')),
                ('sentiment_analysis', models.JSONField(default=dict, help_text='Overall meeting sentiment')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='meetings.meeting')),
            ],
            options={
                'db_table': 'huddle_meeting_summary',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('speaker_id', models.CharField(blank=True, max_length=50, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audio.audiorecording')),
            ],
            options={
                'db_table': 'huddle_transcription_segment',
                'ordering': ['start_time'],
            },
        ),
    ]
