# Generated by Django 4.2.23 on 2025-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiorecording",
            name="deepgram_request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="audiorecording",
            name="transcription_raw",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw API response"
            ),
        ),
        migrations.AddField(
            model_name="audiorecording",
            name="transcription_service",
            field=models.CharField(
                choices=[("deepgram", "Deepgram"), ("whisper", "Whisper")],
                default="deepgram",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transcriptionsegment",
            name="speaker_name",
            field=models.CharField(
                blank=True,
                help_text="Identified speaker name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transcriptionsegment",
            name="words",
            field=models.JSONField(
                blank=True, default=list, help_text="Word-level timing data"
            ),
        ),
    ]
