# Generated by Django 4.2.23 on 2025-09-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_audiorecording_deepgram_request_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiorecording",
            name="transcription_service",
            field=models.CharField(
                default="deepgram",
                help_text="Service used for transcription",
                max_length=20,
            ),
        ),
    ]
