# Generated by Django 4.2.23 on 2025-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0003_alter_audiorecording_transcription_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingsummary",
            name="full_transcript",
        ),
        migrations.RemoveField(
            model_name="meetingsummary",
            name="summary",
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="ai_processing_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="ai_processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="clean_transcript",
            field=models.TextField(
                blank=True, help_text="AI-cleaned and formatted transcript"
            ),
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="decisions_made",
            field=models.JSONField(
                default=list, help_text="Decisions reached during the meeting"
            ),
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="executive_summary",
            field=models.TextField(blank=True, help_text="High-level meeting summary"),
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="is_ai_processed",
            field=models.BooleanField(
                default=False, help_text="Whether AI cleanup and analysis is complete"
            ),
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="raw_transcript",
            field=models.TextField(
                blank=True, help_text="Original verbatim transcript from Deepgram"
            ),
        ),
        migrations.AlterField(
            model_name="meetingsummary",
            name="action_items",
            field=models.JSONField(
                default=list, help_text="Action items with owners and due dates"
            ),
        ),
        migrations.AlterField(
            model_name="meetingsummary",
            name="key_points",
            field=models.JSONField(default=list, help_text="Key discussion points"),
        ),
    ]
