# Generated by Django 4.2.23 on 2025-09-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_add_current_agenda_item"),
        ("audio", "0004_remove_meetingsummary_full_transcript_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionsegment",
            name="agenda_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Agenda item that was active when this segment was recorded",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="meetings.agendaitem",
            ),
        ),
    ]
