# Generated by Django 5.2.5 on 2025-09-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume_level', models.FloatField(blank=True, null=True)),
                ('background_noise', models.FloatField(blank=True, null=True)),
                ('clarity_score', models.FloatField(blank=True, null=True)),
                ('proximity_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='meetings.meetingparticipant')),
            ],
            options={
                'db_table': 'huddle_audio_quality_metric',
            },
        ),
        migrations.CreateModel(
            name='CoordinationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm_version', models.CharField(default='1.0', max_length=20)),
                ('decision_factors', models.JSONField(default=dict)),
                ('backup_recorders', models.ManyToManyField(blank=True, related_name='backup_recordings', to='meetings.meetingparticipant')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordination_decisions', to='meetings.meeting')),
                ('primary_recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recordings', to='meetings.meetingparticipant')),
            ],
            options={
                'db_table': 'huddle_coordination_decision',
            },
        ),
    ]
