# Generated by Django 4.2.23 on 2025-09-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "__first__"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="expected_speakers",
            field=models.JSONField(
                default=list, help_text="List of expected speaker emails"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="known_speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Speakers with existing voice profiles",
                to="core.speakerprofile",
            ),
        ),
    ]
