# Generated by Django 4.2.23 on 2025-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meeting_expected_speakers_meeting_known_speakers"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Physical location for in-person/hybrid meetings",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_link",
            field=models.URLField(
                blank=True, help_text="Virtual meeting link", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_type",
            field=models.CharField(
                choices=[
                    ("in_person", "In Person"),
                    ("virtual", "Virtual"),
                    ("hybrid", "Hybrid"),
                ],
                default="virtual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="scheduled_duration",
            field=models.IntegerField(default=60, help_text="Duration in minutes"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="scheduled_start",
            field=models.DateTimeField(
                blank=True, help_text="Scheduled meeting start time", null=True
            ),
        ),
    ]
