# Generated by Django 4.2.23 on 2025-09-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_meeting_location_meeting_meeting_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="meeting_link",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="meeting_type",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=models.CharField(
                blank=True, help_text="Meeting location", max_length=255
            ),
        ),
    ]
