# Generated by Django 4.2.23 on 2025-09-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_remove_meeting_link_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="is_active",
        ),
        migrations.AddField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("active", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="scheduled",
                help_text="Current meeting status",
                max_length=10,
            ),
        ),
    ]
