# Generated by Django 4.2.23 on 2025-09-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_remove_meeting_is_active_meeting_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(help_text="Agenda item title", max_length=200),
                ),
                (
                    "assigned_participant",
                    models.CharField(
                        blank=True,
                        help_text="Email of participant assigned to this agenda item",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of agenda item"
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "huddle_agenda_item",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
