# Generated by Django 4.2.23 on 2025-09-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_add_agenda_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="current_agenda_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently active agenda item during meeting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_meeting",
                to="meetings.agendaitem",
            ),
        ),
    ]
