# Generated by Django 4.2.23 on 2025-09-24 13:12

import apps.meetings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_add_current_agenda_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address this token is for", max_length=254
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.meetings.models.generate_secure_token,
                        help_text="Secure random token for URL access",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("can_view_transcript", models.BooleanField(default=True)),
                ("can_view_minutes", models.BooleanField(default=True)),
                ("can_view_action_items", models.BooleanField(default=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Token can be deactivated"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiry date", null=True
                    ),
                ),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "huddle_meeting_access_token",
                "indexes": [
                    models.Index(fields=["token"], name="huddle_meet_token_f9687f_idx"),
                    models.Index(
                        fields=["meeting", "email"],
                        name="huddle_meet_meeting_520e93_idx",
                    ),
                ],
                "unique_together": {("meeting", "email")},
            },
        ),
    ]
